
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Button buttonConnect;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textviewDisplay;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView textviewInput;

	private global::Gtk.Button buttonSend;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.buttonConnect = new global::Gtk.Button();
		this.buttonConnect.CanFocus = true;
		this.buttonConnect.Name = "buttonConnect";
		this.buttonConnect.UseUnderline = true;
		this.buttonConnect.Label = global::Mono.Unix.Catalog.GetString("Connect");
		this.vbox1.Add(this.buttonConnect);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.buttonConnect]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textviewDisplay = new global::Gtk.TextView();
		this.textviewDisplay.CanFocus = true;
		this.textviewDisplay.Name = "textviewDisplay";
		this.textviewDisplay.Editable = false;
		this.textviewDisplay.CursorVisible = false;
		this.GtkScrolledWindow.Add(this.textviewDisplay);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w3.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textviewInput = new global::Gtk.TextView();
		this.textviewInput.CanFocus = true;
		this.textviewInput.Name = "textviewInput";
		this.GtkScrolledWindow1.Add(this.textviewInput);
		this.vbox1.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow1]));
		w5.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.buttonSend = new global::Gtk.Button();
		this.buttonSend.Sensitive = false;
		this.buttonSend.CanFocus = true;
		this.buttonSend.Name = "buttonSend";
		this.buttonSend.UseUnderline = true;
		this.buttonSend.Label = global::Mono.Unix.Catalog.GetString("Send");
		this.vbox1.Add(this.buttonSend);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.buttonSend]));
		w6.Position = 3;
		w6.Expand = false;
		w6.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 565;
		this.DefaultHeight = 443;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
